[package]
name = "steel"
version = "0.1.0"
authors = ["Desmond Germans <desmond@germansmedia.nl>"]
edition = "2018"

[lib]
name = "steel"
crate-type = ["rlib"]

[target.x86_64-unknown-linux-gnu.dependencies]
rand = "0.7.2"
e = { path = "e" }
