[package]
name = "pysteel"
version = "0.1.0"
authors = ["Desmond Germans <desmond@germansmedia.nl>"]
edition = "2018"

[lib]
name = "pysteel"
crate-type = ["cdylib"]

[dependencies]
steel = { path = "../", version = "0.1" }
cpython = { version = "0.2", features = ["extension-module"] }
